---
- hosts: localhost
  gather_facts: no
  vars:
   ami_id: "ami-026dea5602e368e96"
  module_defaults:
   group/aws:
    region: "us-east-2"
  tasks:
   - name: Provision Bobs EC2 instance
     ec2:
      key_name: blah
      group: Module5-developer-sg
      instance_type: t3.nano
      image: "{{ ami_id }}"
      instance_tags:
       Name: Module5 Bob
       Module: 5
      wait: yes
      vpc_subnet_id: "{{ public_subnet.subnet.id }}" 
      exact_count: 1
      count_tag:
       Name: Module5 Bob
