---
all:
 hosts:
  ec2-18-221-225-243.us-east-2.compute.amazonaws.com:
  ec2-13-58-133-90.us-east-2.compute.amazonaws.com:
  ec2-3-128-90-175.us-east-2.compute.amazonaws.com:
 children:
  al2:
   hosts:
    ec2-18-221-225-243.us-east-2.compute.amazonaws.com:
    ec2-13-58-133-90.us-east-2.compute.amazonaws.com:
   vars:
    ansible_user: ec2-user
    ansible_python_interpreter: /usr/bin/python
  ubuntu:
   hosts:
    ec2-3-128-90-175.us-east-2.compute.amazonaws.com:
   vars:
     ansible_user: ubuntu
